import type { LucideIcon } from "lucide-react";
import {
  Award,
  BadgeCheck,
  Bolt,
  Bookmark,
  BookOpen,
  Brain,
  Briefcase,
  Bug,
  Calendar,
  Camera,
  Check,
  CheckCircle,
  ChevronUp,
  Circle,
  Clock,
  Cloud,
  Code,
  Coffee,
  Compass,
  Crown,
  Database,
  Diamond,
  Dumbbell,
  Eye,
  Feather,
  File,
  Film,
  Flag,
  Flame,
  Flashlight,
  Folder,
  Gem,
  Gift,
  Globe,
  GraduationCap,
  Guitar,
  Hammer,
  Handshake,
  Heart,
  HeartPulse,
  HelpCircle,
  Hexagon,
  Home,
  Infinity,
  Key,
  Laptop,
  Layers,
  Leaf,
  Library,
  Lightbulb,
  Link,
  Lock,
  Mail,
  Map,
  MapPin,
  Medal,
  MessageCircle,
  Mic,
  Monitor,
  Moon,
  Mountain,
  Music,
  Navigation,
  Palette,
  Pencil,
  Phone,
  Plane,
  Play,
  Plug,
  Plus,
  Podcast,
  Puzzle,
  Rocket,
  RotateCw,
  Ruler,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Ship,
  ShoppingCart,
  Sigma,
  Skull,
  Smile,
  Snowflake,
  Sparkle,
  Sparkles,
  Star,
  Sun,
  Sword,
  Syringe,
  Target,
  Terminal,
  ThumbsUp,
  Timer,
  Tornado,
  TreePine,
  Trophy,
  Truck,
  TvMinimal,
  Umbrella,
  Upload,
  Users,
  Video,
  Wand2,
  Wrench,
  X,
  Zap,
} from "lucide-react";

export interface IconEntry {
  name: string;
  key: string;
  component: LucideIcon;
  tags: string[];
}

export const ICON_REGISTRY: IconEntry[] = [
  { name: "Star", key: "star", component: Star, tags: ["star", "favorite", "rating"] },
  { name: "Trophy", key: "trophy", component: Trophy, tags: ["trophy", "win", "champion"] },
  { name: "Medal", key: "medal", component: Medal, tags: ["medal", "award", "achievement"] },
  { name: "Crown", key: "crown", component: Crown, tags: ["crown", "king", "queen", "royal"] },
  { name: "Award", key: "award", component: Award, tags: ["award", "ribbon", "prize"] },
  { name: "Gem", key: "gem", component: Gem, tags: ["gem", "jewel", "precious"] },
  { name: "Diamond", key: "diamond", component: Diamond, tags: ["diamond", "luxury", "precious"] },
  { name: "Sparkles", key: "sparkles", component: Sparkles, tags: ["sparkle", "magic", "special"] },
  { name: "Sparkle", key: "sparkle", component: Sparkle, tags: ["sparkle", "shine", "glow"] },
  { name: "Zap", key: "zap", component: Zap, tags: ["zap", "lightning", "power", "energy"] },
  { name: "Flame", key: "flame", component: Flame, tags: ["flame", "fire", "hot", "streak"] },
  { name: "Bolt", key: "bolt", component: Bolt, tags: ["bolt", "lightning", "fast"] },
  { name: "Rocket", key: "rocket", component: Rocket, tags: ["rocket", "launch", "speed", "startup"] },
  { name: "Target", key: "target", component: Target, tags: ["target", "goal", "aim", "bullseye"] },
  { name: "Heart", key: "heart", component: Heart, tags: ["heart", "love", "health", "life"] },
  { name: "HeartPulse", key: "heart-pulse", component: HeartPulse, tags: ["heart", "pulse", "health"] },
  { name: "Shield", key: "shield", component: Shield, tags: ["shield", "protect", "defense"] },
  { name: "ShieldCheck", key: "shield-check", component: ShieldCheck, tags: ["shield", "verified", "secure"] },
  { name: "BadgeCheck", key: "badge-check", component: BadgeCheck, tags: ["badge", "verified", "check"] },
  { name: "Check", key: "check", component: Check, tags: ["check", "done", "complete"] },
  { name: "CheckCircle", key: "check-circle", component: CheckCircle, tags: ["check", "circle", "done"] },
  { name: "ThumbsUp", key: "thumbs-up", component: ThumbsUp, tags: ["thumbs", "like", "approve"] },
  { name: "Smile", key: "smile", component: Smile, tags: ["smile", "happy", "face"] },
  { name: "Sun", key: "sun", component: Sun, tags: ["sun", "bright", "day", "light"] },
  { name: "Moon", key: "moon", component: Moon, tags: ["moon", "night", "dark"] },
  { name: "Snowflake", key: "snowflake", component: Snowflake, tags: ["snow", "ice", "winter", "cold"] },
  { name: "Leaf", key: "leaf", component: Leaf, tags: ["leaf", "nature", "eco", "green"] },
  { name: "TreePine", key: "tree-pine", component: TreePine, tags: ["tree", "nature", "forest"] },
  { name: "Mountain", key: "mountain", component: Mountain, tags: ["mountain", "climb", "peak", "summit"] },
  { name: "Compass", key: "compass", component: Compass, tags: ["compass", "explore", "navigate"] },
  { name: "Navigation", key: "navigation", component: Navigation, tags: ["navigation", "direction", "arrow"] },
  { name: "Globe", key: "globe", component: Globe, tags: ["globe", "world", "earth", "global"] },
  { name: "Map", key: "map", component: Map, tags: ["map", "explore", "travel"] },
  { name: "MapPin", key: "map-pin", component: MapPin, tags: ["map", "pin", "location"] },
  { name: "Flag", key: "flag", component: Flag, tags: ["flag", "milestone", "country"] },
  { name: "Bookmark", key: "bookmark", component: Bookmark, tags: ["bookmark", "save", "favorite"] },
  { name: "Key", key: "key", component: Key, tags: ["key", "access", "unlock", "secret"] },
  { name: "Lock", key: "lock", component: Lock, tags: ["lock", "secure", "private"] },
  { name: "Lightbulb", key: "lightbulb", component: Lightbulb, tags: ["lightbulb", "idea", "innovation"] },
  { name: "Brain", key: "brain", component: Brain, tags: ["brain", "smart", "intelligence", "think"] },
  { name: "GraduationCap", key: "graduation-cap", component: GraduationCap, tags: ["graduation", "education", "school"] },
  { name: "BookOpen", key: "book-open", component: BookOpen, tags: ["book", "read", "learn", "study"] },
  { name: "Library", key: "library", component: Library, tags: ["library", "books", "knowledge"] },
  { name: "Pencil", key: "pencil", component: Pencil, tags: ["pencil", "write", "edit", "draw"] },
  { name: "Ruler", key: "ruler", component: Ruler, tags: ["ruler", "measure", "precision"] },
  { name: "Palette", key: "palette", component: Palette, tags: ["palette", "art", "paint", "creative"] },
  { name: "Feather", key: "feather", component: Feather, tags: ["feather", "write", "light", "quill"] },
  { name: "Code", key: "code", component: Code, tags: ["code", "developer", "programming"] },
  { name: "Terminal", key: "terminal", component: Terminal, tags: ["terminal", "command", "cli", "hacker"] },
  { name: "Bug", key: "bug", component: Bug, tags: ["bug", "debug", "fix", "insect"] },
  { name: "Database", key: "database", component: Database, tags: ["database", "data", "storage"] },
  { name: "Laptop", key: "laptop", component: Laptop, tags: ["laptop", "computer", "tech"] },
  { name: "Monitor", key: "monitor", component: Monitor, tags: ["monitor", "screen", "desktop"] },
  { name: "Settings", key: "settings", component: Settings, tags: ["settings", "gear", "config"] },
  { name: "Wrench", key: "wrench", component: Wrench, tags: ["wrench", "tool", "repair", "fix"] },
  { name: "Hammer", key: "hammer", component: Hammer, tags: ["hammer", "build", "construct"] },
  { name: "Plug", key: "plug", component: Plug, tags: ["plug", "connect", "power"] },
  { name: "Wand", key: "wand", component: Wand2, tags: ["wand", "magic", "wizard"] },
  { name: "Puzzle", key: "puzzle", component: Puzzle, tags: ["puzzle", "solve", "piece", "game"] },
  { name: "Layers", key: "layers", component: Layers, tags: ["layers", "stack", "level"] },
  { name: "Infinity", key: "infinity", component: Infinity, tags: ["infinity", "endless", "forever"] },
  { name: "Sigma", key: "sigma", component: Sigma, tags: ["sigma", "math", "sum", "total"] },
  { name: "Clock", key: "clock", component: Clock, tags: ["clock", "time", "watch"] },
  { name: "Timer", key: "timer", component: Timer, tags: ["timer", "countdown", "stopwatch"] },
  { name: "Calendar", key: "calendar", component: Calendar, tags: ["calendar", "date", "schedule"] },
  { name: "RotateCw", key: "rotate-cw", component: RotateCw, tags: ["rotate", "refresh", "cycle"] },
  { name: "ChevronUp", key: "chevron-up", component: ChevronUp, tags: ["up", "level", "rank"] },
  { name: "Dumbbell", key: "dumbbell", component: Dumbbell, tags: ["dumbbell", "gym", "fitness", "strong"] },
  { name: "Sword", key: "sword", component: Sword, tags: ["sword", "battle", "warrior", "fight"] },
  { name: "Skull", key: "skull", component: Skull, tags: ["skull", "danger", "death", "hardcore"] },
  { name: "Tornado", key: "tornado", component: Tornado, tags: ["tornado", "storm", "power", "chaos"] },
  { name: "Flashlight", key: "flashlight", component: Flashlight, tags: ["flashlight", "search", "discover"] },
  { name: "Eye", key: "eye", component: Eye, tags: ["eye", "see", "watch", "observe"] },
  { name: "Search", key: "search", component: Search, tags: ["search", "find", "discover"] },
  { name: "Users", key: "users", component: Users, tags: ["users", "group", "team", "community"] },
  { name: "Handshake", key: "handshake", component: Handshake, tags: ["handshake", "deal", "partner"] },
  { name: "MessageCircle", key: "message-circle", component: MessageCircle, tags: ["message", "chat", "talk"] },
  { name: "Mail", key: "mail", component: Mail, tags: ["mail", "email", "letter"] },
  { name: "Send", key: "send", component: Send, tags: ["send", "share", "message"] },
  { name: "Share2", key: "share", component: Share2, tags: ["share", "social", "network"] },
  { name: "Link", key: "link", component: Link, tags: ["link", "chain", "connect"] },
  { name: "Upload", key: "upload", component: Upload, tags: ["upload", "submit", "publish"] },
  { name: "Cloud", key: "cloud", component: Cloud, tags: ["cloud", "online", "storage"] },
  { name: "Gift", key: "gift", component: Gift, tags: ["gift", "present", "reward", "bonus"] },
  { name: "ShoppingCart", key: "shopping-cart", component: ShoppingCart, tags: ["cart", "shop", "buy"] },
  { name: "Briefcase", key: "briefcase", component: Briefcase, tags: ["briefcase", "work", "business"] },
  { name: "Home", key: "home", component: Home, tags: ["home", "house", "base"] },
  { name: "Plane", key: "plane", component: Plane, tags: ["plane", "travel", "fly"] },
  { name: "Ship", key: "ship", component: Ship, tags: ["ship", "boat", "sail", "voyage"] },
  { name: "Truck", key: "truck", component: Truck, tags: ["truck", "deliver", "ship"] },
  { name: "Camera", key: "camera", component: Camera, tags: ["camera", "photo", "picture"] },
  { name: "Video", key: "video", component: Video, tags: ["video", "record", "film"] },
  { name: "Film", key: "film", component: Film, tags: ["film", "movie", "cinema"] },
  { name: "Music", key: "music", component: Music, tags: ["music", "note", "song"] },
  { name: "Guitar", key: "guitar", component: Guitar, tags: ["guitar", "music", "instrument"] },
  { name: "Mic", key: "mic", component: Mic, tags: ["mic", "microphone", "speak", "podcast"] },
  { name: "Podcast", key: "podcast", component: Podcast, tags: ["podcast", "audio", "listen"] },
  { name: "Phone", key: "phone", component: Phone, tags: ["phone", "call", "mobile"] },
  { name: "TvMinimal", key: "tv", component: TvMinimal, tags: ["tv", "screen", "watch"] },
  { name: "Coffee", key: "coffee", component: Coffee, tags: ["coffee", "drink", "morning", "energy"] },
  { name: "Umbrella", key: "umbrella", component: Umbrella, tags: ["umbrella", "rain", "protect"] },
  { name: "Syringe", key: "syringe", component: Syringe, tags: ["syringe", "medical", "health"] },
  { name: "Play", key: "play", component: Play, tags: ["play", "start", "begin", "game"] },
  { name: "Plus", key: "plus", component: Plus, tags: ["plus", "add", "new", "create"] },
  { name: "X", key: "x", component: X, tags: ["x", "close", "delete", "cross"] },
  { name: "Hexagon", key: "hexagon", component: Hexagon, tags: ["hexagon", "shape", "hex"] },
  { name: "Circle", key: "circle", component: Circle, tags: ["circle", "round", "shape"] },
  { name: "HelpCircle", key: "help-circle", component: HelpCircle, tags: ["help", "question", "support"] },
  { name: "File", key: "file", component: File, tags: ["file", "document", "page"] },
  { name: "Folder", key: "folder", component: Folder, tags: ["folder", "directory", "organize"] },
];

export const ICON_MAP: Record<string, IconEntry> = Object.fromEntries(
  ICON_REGISTRY.map((entry) => [entry.key, entry]),
);
